### ISSUE TITLE
Unable to run qnib/collabtive

### ISSUE THREAD

**Issue by ovpc** [ChristianKniep/docker-collabtive#2]
~ $ sudo docker run --privileged -d --name collab -v /dev/urandom:/dev/urandom \ -v /dev/random:/dev/random -v /dev/null:/dev/null \ -p 8181:80 qnib/collabtive
Unable to find image ' -v' locally
2014/09/22 10:01:42 Invalid repository name ( -v), only [a-z0-9-_.] are allowed

Just out of interest.
With or without the added "--name collab", same result.

**Comment by ChristianKniep** [comment]
It seems to me that the command has a flaw. The command complains about 
   Unable to find image ' -v' locally

That indicates that `-v` is not recognized as an option but the first argument, which describes the image name.
Please make sure that you do not have linebreaks and that the columns are correct. Maybe skips the linebreaks.

**Comment by ChristianKniep** [comment]
Added within README.md
