### ISSUE TITLE
unable to start 

### ISSUE THREAD

**Issue by ghost** [ChristianKniep/docker-collabtive#3]
docker run --privileged -d -v /dev/urandom:/dev/urandom \ -v /dev/random:/dev/random -v /dev/null:/dev/null \ -p 8181:80 qnib/collabtive
Unable to find image ' -v' locally

centos 7.x

**Comment by ChristianKniep** [comment]
It seems  to me that you added a weird line break of aome sort.
The first argument is '-v', thus the bash is not picking up the option. 

Please kick out all linebreaks and slashes.

Cheers

**Comment by ChristianKniep** [comment]
Did this help you out? If so, please close the issue.

thx for your feedback

**Comment by ChristianKniep** [comment]
Put it into the README.md

**Comment by ghost** [comment]
Ill be away from it for a week for vacation. Ill close it now if you want.
But that was a copy and paste. So will have to just retype it manually, and
see if that makes a difference.

**Comment by ghost** [comment]
Could you paste here what it should look like? Maybe its a rendering issue

**Comment by ChristianKniep** [comment]
Hey,

here you go...

```
docker run --privileged -d -v /dev/urandom:/dev/urandom -v /dev/random:/dev/random -v /dev/null:/dev/null  -p 8181:80 qnib/collabtive
```
